title: COC wiki
description: Official wiki and tutorials
show_downloads: false
git_branch: master
logo_url: http://wiki.codeofcubes.com/img/coc-logo.png
google_analytics:
theme: 
wiki_folder: p
use_github_wiki: false
use_prose_io: true
google_cse_token: 
comments: false
custom_head: false
custom_sidebar: true
custom_footer: false
gems:
  - jekyll-sitemap
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-feed
